name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazendo checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurando o Docker Buildx (necessário para construir a imagem)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Passo 3: Fazendo login no Docker Hub (ou AWS ECR)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Armazenado em GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Armazenado em GitHub Secrets

      # Passo 4: Construindo a imagem Docker e fazendo o push
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/login-register-service:${{ github.sha }}  # Usando o SHA do commit como versão

         # Passo 4: Construindo a imagem Docker e fazendo o push
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/login-register-service:latest  # Usando o SHA do commit como versão

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    
          
      - name: Deploy via Bastion Host
        run: |
            sudo docker pull s041maya/login-register-service:latest
            sudo docker stop meu-container || true
            sudo docker rm meu-container || true
            sudo docker run -d --name meu-container -p 8001:8001 s041maya/login-register-service:latest
         
